spring.application.name=proyecto_tfg_api

# ===============================
# DATASOURCE SUPABASE (PostgreSQL)
# ===============================

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?user=postgres.mtzbxucntcfxiitpryek&password=24092004zuralDB*&prepareThreshold=0
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true